# version: '3.8'

# services:
#     app:
#         build: .
#         container_name: backend-app
#         ports:
#             - '3000:3000'
#         environment:
#             MYSQL_HOST: mysql
#             MYSQL_PORT: 3306
#             MYSQL_USERNAME: root
#             MYSQL_PASSWORD: kiit@123
#             MYSQL_DATABASE: cms
#             REDIS_HOST: redis
#             REDIS_PORT: 6379
#             MONGO_URI: mongodb://mongo:27017
#             MONGO_DB_NAME: yourMongoDb
#             ELASTICSEARCH_HOST: http://elasticsearch:9200
#             ELASTICSEARCH_USERNAME: elastic
#             ELASTICSEARCH_PASSWORD: BD0wY*6saeWSdorUp3*O
#         depends_on:
#             - mysql
#             - redis
#             - mongo
#             - elasticsearch
#         networks:
#             - cms-network

#     mysql:
#         image: mysql:8.0
#         container_name: mysql
#         environment:
#             MYSQL_ROOT_PASSWORD: kiit@123
#             MYSQL_DATABASE: cms
#         ports:
#             - '3307:3306'
#         volumes:
#             - mysql-data:/var/lib/mysql
#             - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
#         networks:
#             - cms-network

#     redis:
#         image: redis:alpine
#         container_name: redis
#         ports:
#             - '6379:6379'
#         networks:
#             - cms-network

#     mongo:
#         image: mongo:latest
#         container_name: mongo
#         ports:
#             - '27017:27017'
#         networks:
#             - cms-network

#     elasticsearch:
#         image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
#         container_name: elasticsearch
#         environment:
#             - discovery.type=single-node
#             - xpack.security.enabled=false
#         ports:
#             - '9200:9200'
#             - '9300:9300'
#         networks:
#             - cms-network

# volumes:
#     mysql-data:
#     es-data:

# networks:
#     cms-network:
#         driver: bridge

version: '3.8'

services:
    app:
        build: .
        container_name: backend-app
        ports:
            - '3000:3000'
        environment:
            MYSQL_HOST: mysql
            MYSQL_PORT: 3306
            MYSQL_USERNAME: root
            MYSQL_PASSWORD: kiit@123
            MYSQL_DATABASE: cms
            REDIS_HOST: redis
            REDIS_PORT: 6379
            MONGO_URI: mongodb://mongo:27017
            MONGO_DB_NAME: yourMongoDb
            ELASTICSEARCH_HOST: http://elasticsearch:9200
            ELASTICSEARCH_USERNAME: elastic
            ELASTICSEARCH_PASSWORD: BD0wY*6saeWSdorUp3*O
            RABBITMQ_HOST: rabbitmq
            RABBITMQ_PORT: 5672
            RABBITMQ_USER: guest
            RABBITMQ_PASSWORD: guest
        depends_on:
            - mysql
            - redis
            - mongo
            - elasticsearch
            - rabbitmq
        networks:
            - cms-network

    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: kiit@123
            MYSQL_DATABASE: cms
        ports:
            - '3307:3306'
        volumes:
            - mysql-data:/var/lib/mysql
            - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
        networks:
            - cms-network

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - '6379:6379'
        networks:
            - cms-network

    mongo:
        image: mongo:latest
        container_name: mongo
        ports:
            - '27017:27017'
        networks:
            - cms-network

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
        ports:
            - '9200:9200'
            - '9300:9300'
        networks:
            - cms-network

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmqu
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        ports:
            - '5672:5672' # AMQP protocol port
            - '15672:15672' # RabbitMQ management UI port
        networks:
            - cms-network

volumes:
    mysql-data:
    es-data:

networks:
    cms-network:
        driver: bridge
